Tencent/wepy

README.md
·图片居中显示
·所有链接新窗口打开
·目录结构增加树状图与说明
第一次pr，其实文档还有很多看不懂的地方，准备模仿vue的文档，把wepy文档做的更细致易读= =
=> 修改了一些文档的样式

packages/wepy-web/src/components/progress.vue
=> added progress component

packages/wepy-plugin-replace/README.md, packages/wepy-plugin-replace/src/index.js
使 wepy-plugin-replace 的一个 setting 下的 config 支持 Array 等形式，实现一个 filter 支持多个替换规则。
=> Enhance ‘wepy-plugin-replace’

packages/wepy-web/src/components/checkbox.vue, packages/wepy-web/src/components/radio.vue
fixed [WARNING] [xmldom warning] unclosed xml
=> update checkbox && radio

README.md, docs/README.md, docs/api.md, docs/document.md, docs/server.js
We are using Wepy in our current project and found it helpful. Thanks for the great work!
I was reading the documents this morning. I meant to fix a typo (`bable` -> `babel`) but end up with a lot of improvements and this pull request. 🤣 
Here's some of the improvements:
* some typos fixed (`bable`, `sciprt `)
* readability of Markdown source.
* some typography improvements, etc. lists
* an error when previewing while developing (see `docs/server.js`)
* syntax highlighting guide for VIM
I hope it will be helpful.
=> Documentation improved

package-lock.json, packages/wepy-cli/package-lock.json, packages/wepy-cli/src/compile-wpy.js, packages/wepy-cli/src/util.js
支持私有组件引用 [issues 342](https://github.com/wepyjs/wepy/issues/342)
=> import 带有命名空间@符号的私有组件

README.md
一直忘记添加到使用者里，感谢wepy让我一个后端可以做出这么"大"的小程序。
=> Add 坚橙 to WePY users in readme file

docs/data/cases.json
谢谢提醒在这里可以加。
好奇怪，我上一个pr之后不知道为啥ff merge不回来了，删了又重新fork了一次哈哈。
=> Add 坚橙 to 应用案例

docs/data/cases.json
基于wepy框架重构了天天跟我买整个小程序，
天天跟我买，提供海内外好货折扣信息。
正品特卖、海淘好货、教你品质生活的导购
=> add 小程序 天天跟我买

docs/css/style.css, docs/index.html, docs/less/slides/slide-feature.less
=> Fix tootip bug

docs/data/cases.json
=> GitHub 掘金版

docs/data/cases.json
=> add ufutx wepy mp

docs/data/cases.json
班级群管 小程序 从立项就使用了wepy, 后面也会一如既往的支持，共同推动wepy 越来越好，望收纳
=> add comb school case

docs/data/cases.json
=> add NewsLite to 应用案例

docs/data/cases.json
=> cases: update 友福图书馆案

README.md
=> cases：added NewsLite

packages/wepy-cli/src/compile-script.js, packages/wepy-cli/src/compile.js, packages/wepy-cli/src/web/compile-script.js
增加支持引用typescript 的ts文件
import  .ts
=> support import .ts 

packages/wepy-cli/templates/template/src/pages/index-redux.wpy, packages/wepy-cli/templates/template/src/pages/index.wpy
=> fix issue #709

packages/wepy-cli/templates/empty/wepy.config.js, packages/wepy-cli/templates/template/wepy.config.js
1. 优化 wepy-cli 配置文件 "wepy.config.js";
2. 修正 “delete module.exports.compilers.babel.sourcesMap“ 中的 “sourcesMap” 单词拼写错误。
- [x ] `npm run test` passes
=> 优化 wepy 配置文件

docs/md/api.md
intercept request 例子中, return 语句消失
=> intercept request 例子中, return 语句消失

docs/md/doc.md
=> add full name to ES6()

docs/data/cases.json
=> 添加时光倒数日的案例

packages/wepy/src/base.js, packages/wepy/src/component.js, packages/wepy/test/fake/mixin.js, packages/wepy/test/fake/page.js
=> fix: mixins 里的生命周期函数执行时机应该优先于组件

docs/data/cases.json
=> 增加开源小程序应用全球排行榜

README.md
=> 添加开源小程序，应用全球排行

docs/data/cases.json
=> add ufutx love case

packages/wepy-redux/src/connect/index.js
fix bug https://github.com/Tencent/wepy/issues/976
=> make this in @connect steadily point to component instance connected

docs/data/cases.json, docs/data/donate.json, docs/md/doc.md, packages/wepy-cli/src/compile-style.js, packages/wepy-cli/src/util.js
修复scope npm包require的问题。
scope npm包都是以@开头，如@mnui/toptips其实是一个npm包的名字，不应该直接用/去分割包名。
=> fix scope npm packages

packages/wepy/src/base.js
=> 修复App的onLaunch等生命周期函数中$wxapp为undefined的问题

README.md
edit and change styus to stylus
=> Update README.md change styus to stylus

README.md
=> 添加we川大[开源]到readme

packages/wepy/src/mixin.js
加入了对computed属性混合的支持
1. 解决https://github.com/Tencent/wepy/issues/859
2. 使得wepy-redux能够支持@connect到mixin
=> support computed mixins

README.md
[README 中 DOME 错误](https://github.com/Tencent/wepy/issues/1070)
=> 修复 README.md 文件中的 DOME 错误

packages/wepy/src/base.js, packages/wepy/src/component.js, packages/wepy/src/page.js
相关说明：https://github.com/Tencent/wepy/issues/1016
=> 加入了Component的onUnload实现

docs/data/donate.json
=> Revert "update donate.json"

README.md, docs/md/doc.md, packages/wepy-compiler-postcss/.npmignore, packages/wepy-compiler-postcss/README.md, packages/wepy-compiler-postcss/package.json, packages/wepy-compiler-postcss/src/index.js
=> 新增 wepy-compiler-postcss

packages/wepy/src/component.js
=> 修复coerce中this指向的问题

docs/md/doc.md
updated line 410 to new init project syntax
=> changed line 410 to new syntax

packages/wepy/src/base.js
=> fix 修改微信小程序1.1.1版本中this不包含options

docs/md/doc.md
- [X ] documentation is changed or added
=> Update doc.md  -- The link to API document is invalid

packages/wepy/src/app.js
修复 issue https://github.com/Tencent/wepy/issues/1319
=> fix 自定义分析API 上报丢失参数 - https://github.com/Tencent/wepy/issues/1319

packages/wepy-redux/package.json
=> update 1.7.x: fixed #1276 && publish wepy-redux v1.5.8

docs/data/cases.json
=> Update Ufutx Party

docs/data/cases.json
=> Add Ufutx Party

packages/wepy-plugin-autoprefixer/package.json, packages/wepy-plugin-autoprefixer/src/index.js
=> Fixes #1286

packages/wepy-cli/core/parseTemplate.js, packages/wepy-cli/package.json, packages/wepy-cli/test/core/parseTemplate.test.js
=> update test case && fixed parseTemplate

packages/wepy-cli/src/util.js
=> replace '`'

.editorconfig, package.json, packages/wepy/src/component.js, packages/wepy/src/util.js, packages/wepy/test/index.js, packages/wepy/test/util.js
=> 优化 Immutable 数据类型在 this.setData() 时的性能问题

packages/wepy-cli/src/compile-script.js, packages/wepy-cli/src/compile-wpy.js
https://github.com/Tencent/wepy/issues/1267
=> Fix - 解决引入第三方组件无法正确解析拷贝依赖；解决第三方组件导出多个组件错误

packages/wepy-cli/src/bin/wepy-devtool.js, packages/wepy-cli/src/bin/wepy.js
=> fix: optimize devtool commanders

docs/data/cases.json
=> 球迷Battle赛  开源项目申请

CONTRIBUTING.md
=> docs(CONTRIBUTING.md): Fixed typo "npm run bootstrap:prod"

packages/wepy/test/wxfake.js
=> change gloabl -> global

packages/wepy-cli/core/compile.js
=> fix: added no pages config exception handling

packages/wepy-compiler-typescript/README.md
the module system should be commonjs
=> update wepy-compiler-typescript readme

packages/wepy-compiler-less/createPlugin.js
=> fix: fix typo

packages/wepy-cli/core/plugins/template/parse.js, packages/wepy-cli/test/config.js, packages/wepy-cli/test/core/fixtures/template/assert/v-if.wxml, packages/wepy-cli/test/core/fixtures/template/original/v-if.wxml, packages/wepy-cli/test/core/plugins/template/parse.test.js
=> chore: added template parser test case

docs/data/cases.json
=> add 日日課 to cases

packages/wepy-web/src/components/image.vue
=> feat: add image component for wepy-web

CONTRIBUTING.md, CONTRIBUTING_COMMIT.md
=> doc: Update CONTRIBUTING_COMMIT.md and CONTRIBUTIN.md

packages/wepy-cli/core/compile.js, packages/wepy-cli/core/parseOptions.js
=> feat: added static output

packages/cli/core/parseOptions.js
=> fix(cli): fix parse options

docs/data/cases.json
=> 添加武侯的猫案例,切到master pr

packages/wepy-plugin-filemin/src/index.js
=> 添加对支付宝小程序axml文件的识别

packages/core/weapp/init/lifecycle.js
=> 用ES6 style修改了冗余for逻辑

docs/data/cases.json
=> 更新cases.json

docs/data/cases.json
=> 增加盛夏光年科技有限公司的案例

docs/data/cases.json
=> 申请添加【旅行者一号Lite】案例

packages/core/dist/wepy.js, packages/core/weapp/class/Base.js, packages/core/weapp/init/lifecycle.js
统一了一下实例的初始化选项 ```$options``` (和Vue保持一致)
=> fix(core): fixed typo

docs/data/cases.json
=> 添加“书幽阁“ 案例

packages/cli/core/plugins/template/attrs/index.js, packages/cli/core/plugins/template/attrs/ref.js, packages/core/dist/wepy.js, packages/core/weapp/init/lifecycle.js, packages/core/weapp/init/methods.js
e.g:
``` vue
<template>
<counter ref="countRef" @index-emit.user="counterEmit" />
</template>
<script>
import wepy from '@wepy/core'
wepy.page({
created () {
// 打印count组件实例
console.log(this.$refs.countRef)
}
})
</script>
```
=>  feat: support ref

packages/cli/core/compile.js
分包这个，之前的编译
参考1.7写的。2.0本身的没有处理循环，我修复之后测试正常了。
=> 修复2.0分包的问题by Easyxcx 2.0.x

packages/core/dist/wepy.js, packages/core/weapp/class/WepyPage.js, packages/core/weapp/component.js, packages/core/weapp/init/lifecycle.js, packages/core/weapp/init/mixins.js
添加了Page生命周期，包含：
- ```onLoad```
- ```onShow```
- ```onHide```
- ```onUnload```
- ```onPullDownRefresh```
- ```onReachBottom```
- ```onShareAppMessage```
- ```onPageScroll```
- ```onTabItemTap```
=> feat(core): added page lifecycles

packages/core/weapp/component.js
=> feat(core): support component options

docs/data/cases.json
=> 申请添加【场景小程序】案例

packages/wepy-cli/templates/empty/.eslintrc.js, packages/wepy-cli/templates/template/.eslintrc.js
修改了模板中的 .eslintrc.js
- 增加了全局对象'wx'以免eslint报错
=> feat: add 'wx' as global object

packages/cli/core/init/plugin.js, packages/cli/test/core/init/plugin.test.js
=> fix(cli): added check for plugins

docs/data/cases.json
=> 添加RssFeed(rss订阅工具)

packages/compiler-less/createPlugin.js, packages/compiler-less/test/fixtures/css/function.css, packages/compiler-less/test/fixtures/css/list-each.css, packages/compiler-less/test/fixtures/css/list.css, packages/compiler-less/test/fixtures/less/list-each.less, packages/compiler-less/test/fixtures/less/list.less, packages/compiler-less/test/helpers/lessc.js, packages/compiler-less/test/helpers/specs.js
https://github.com/dlhandsome/wepy-2.0-alpha-feedback/issues/20
=> fix(compiler-less): fixed less image-width with error.

docs/md/api.md
=> docs: update api.md

packages/wepy-plugin-replace/src/index.js
=> fix(wepy-plugin-replace): 修复1.7.x replace插件配置多个object内容未替换的问题

docs/data/cases.json
Fixed an issue caused by json data not being standardized （https://tencent.github.io/wepy/ ）
=> fix(bug): the error of case

packages/core/shared/extend.js
=> style(core): code indent

packages/cli/core/plugins/compiler/index.js
fixed https://github.com/dlhandsome/wepy-2.0-alpha-feedback/issues/28
=> fix(cli): output right deps wxss

packages/core/weapp/class/WepyApp.js
=> fix: fix babel error

packages/wepy-compiler-less/package.json
Update the version of less to support new modern features like `Properties as Variables` as described [here](http://lesscss.org/features/#variables-feature-properties-as-variables-new-). I went through the code and tested it that I just need to update the version defined in `package.json` to make it works. Any other code do not need to modify.
=> Update the version of less

packages/wepy-cli/src/compile-template.js
添加 s-else 到 BOOLEAN_ATTRS 中，替换xmldom生成的无值属性
=> fix(cli): added s-else to BOOLEAN_ATTRS

packages/plugin-eslint/README.md, packages/plugin-eslint/index.js, packages/plugin-eslint/package-lock.json, packages/plugin-eslint/package.json
如果此选项设置为true，插件将仅处理和报告错误，忽略警告
```javascript
const eslint = require('@wepy/plugin-eslint');
module.exports = {
plugins: [
eslint({
quiet: true
})
]
};
```
启用 ```ESLint``` 自动修复功能
注意：此选项将更改源文件
启用 ```ESLint```
用于 ```linting``` 的 ```ESLint``` 实例的路径
用于格式化 ```ESLint``` 输出，选项值接收字符串或者函数
```javascript
const eslint = require('@wepy/plugin-eslint');
module.exports = {
plugins: [
eslint({
// default value
formatter: require('eslint/lib/formatters/stylish'),
// community formatter
formatter: require('eslint-friendly-formatter'),
// custom formatter
formatter: function(results) {
// `results` format is available here
// http://eslint.org/docs/developer-guide/nodejs-api.html#executeonfiles()
// you should return a string
// DO NOT USE console.*() directly !
return 'OUTPUT'
}
})
]
};
```
=> feat(plugin-eslint): added quiet/fix/formatter options

packages/cli/core/compile.js
fix: https://github.com/Tencent/wepy/issues/1944
=> fix(cli): fixed save file in the IDE multiple times with errors

docs/index.html
=> FIX index doc typo

docs/md/doc.md
将 其它优化细节章节(位于左侧索引底部) 下的一些超链接地址更新 / 修复
- 互换 <3. 改变数据绑定方式> 与 <4. 组件代替模板和模块> 的超链接地址（之前写反了）
- 修改 <1. wx.request 接收参数修改> 下的官方文档地址为 新版本的 wx.request 文档
- 更新 <2. 优化事件参数传递> 为新版本的官方文档地址
// 不小心点到了超链接发现地址有点问题就改了...
=> doc: 修改了 其他优化细节 的子章节连接到官方文档的超链接

docs/data/cases.json
=> 【申请】添加case: 招商银行信用卡中心

docs/data/cases.json
=> 【申请】添加case: Scrum敏捷估算

packages/wepy-cli/package.json
=> release(wepy-cli): 1.7.3-alpha6

packages/wepy-cli/src/compile-template.js
=> fix: 修复了模版编译时判断条件多了一个:问题

packages/core/dist/wepy.js, packages/core/weapp/apis/mixin.js, packages/core/weapp/init/mixins.js
support multiple global mixins
```javascript
wepy.mixin([
{ // mixin1 },
{ // mixin2 }
])
```
```javascript
wepy.mixin({ // mixin1 })
wepy.mixin({ // mixin2 })
```
=> feat: support multiple global mixins

packages/core/dist/wepy.js, packages/core/weapp/init/mixins.js
fix https://github.com/Tencent/wepy/commit/82fe2f7c2a40168bd48ca09aa67c47c9dae8fac9#commitcomment-31939179
=> fix: added default global mixin

packages/cli/package.json
=> Fixes https://github.com/Tencent/wepy/issues/2021

packages/cli/core/plugins/build/app.js, packages/cli/core/plugins/build/assets.js, packages/cli/core/plugins/build/components.js, packages/cli/core/plugins/build/pages.js, packages/cli/core/plugins/build/vendor.js
=> fix(cli): fixed script-dep-fix & script-injection implementation modalities

docs/md/doc.md
=> 普通组件引用的--index.wpy中的wepy.component应改为wepy.page

docs/md/doc.md
=> 跟上个我发现的问题一致，请修改。

docs/md/doc.md
后面不知道还有没有这个错误，你们自己仔细检查一遍，我想进腾讯见见龙哥，给个机会吧
=> index.wpy怎么会使用wpy.component呢，我怀疑你们是复制粘贴的，哈哈，开玩笑的

packages/wepy-cli/package.json
https://github.com/Tencent/wepy/pull/2032
=> release(wepy-cli): 1.7.3-alpha7

packages/core/dist/wepy.js, packages/core/weapp/init/lifecycle.js
=>  feat(core): added ready/moved/detached lifecycle

packages/core/dist/wepy.js, packages/core/weapp/component.js, packages/core/weapp/init/index.js, packages/core/weapp/init/relations.js
- support relations options
example:
```javascript
wepy.component({
relations: {
'./child'
},
ready () {
const node = this.$wx.getRelationNodes('child')
console.log('==== child nodes =====', nodes)
}
})
```
=>  feat(core): added relations patch

packages/compiler-babel/package.json
=> release: @wepy/compiler-babel@2.0.3

packages/compiler-typescript/index.js
=> fix(compiler-typescript): fixed missing options

packages/core/package.json
=> release: @wepy/core@2.0.0-alpha.3

scripts/npm_publish/lib/interact.js
=> chore(publish): added current version info

packages/cli/core/plugins/template/directives/v-on.js, packages/core/dist/wepy.js, packages/core/weapp/init/events.js, packages/core/weapp/init/methods.js
=> fix(core): fixed component customer event

packages/core/dist/wepy.js, packages/core/weapp/init/events.js
=>  fix(core): fixed initEvent

docs/data/cases.json
=> added case

README.md, docs/data/cases.json, package-lock.json
=> 添加“南京邮电大学”案例

packages/cli/core/plugins/helper/generateCodeFrame.js
=> fix(cli): misspell originalPositionFor

package-lock.json, packages/x/README.md, packages/x/dist/index.js, packages/x/index.js, packages/x/package.json, scripts/config.js
=> feat(x): added es export

packages/core/dist/wepy.js, packages/core/weapp/wepy.js, packages/use-promisify/dist/index.js, packages/use-promisify/index.js, packages/x/dist/index.js, packages/x/index.js, scripts/config.js
=> chore(build): pkg version support

.github/ISSUE_TEMPLATE.md
=> chore: fix syntax errors in the ISSUE_TEMPLATE.md

packages/compiler-babel/README.md, packages/compiler-less/README.md, packages/compiler-sass/README.md, packages/core/dist/wepy.js, packages/core/weapp/init/lifecycle.js
=> docs: fixed install guide

packages/core/dist/wepy.js, packages/core/weapp/init/lifecycle.js
=> fix(core): fixed page lifecycle typo

packages/cli/core/plugins/parser/script.js
避免重复深度遍历 npm 依赖，不然在一些引入关系复杂的项目里会出现内存溢出
我现在的项目就是，不修改无法打包
=> refactor(cli): 避免重复深度遍历 npm 依赖

packages/cli/core/plugins/scriptDepFix.js, packages/compiler-babel/index.js
=> feat: add support for @babel/preset-typescript, allow babel-compiler to compile typescript

packages/wepy/src/app.js
doc: https://developers.weixin.qq.com/miniprogram/dev/framework/ability/network.html#%E4%BD%BF%E7%94%A8%E9%99%90%E5%88%B6
=> update: max request

packages/core/weapp/init/lifecycle.js, packages/core/weapp/init/watch.js
fix(core): computed 不能被 watch
初始化顺序有问题
=> fix(core): computed 不能被 watch

packages/core/weapp/init/lifecycle.js, packages/core/weapp/init/props.js, packages/core/weapp/init/render.js, packages/core/weapp/init/watch.js, packages/core/weapp/observer/watcher.js
refactor(core): 优化 computed ，恢复惰性求值
惰性求值还是一个很重要的特性的。
直接引用 vue 的解释：
> 我们为什么需要缓存？假设我们有一个性能开销比较大的计算属性 A，它需要遍历一个巨大的数组并做大量的计算。然后我们可能有其他的计算属性依赖于 A 。如果没有缓存，我们将不可避免的多次执行 A 的 getter！如果你不希望有缓存，请用方法来替代。
=> refactor(core): 优化 computed ，恢复惰性求值

packages/core/weapp/apis/index.js, packages/redux/helper.js, packages/redux/install.js
refactor(redux): 重构 redux，
1. 优化性能，只有变化的才更新
2. 可被观察，将其包含进 observer 里，可以被 watch 以及被其它 compued 依赖
=> refactor(redux): 重构 redux，优化性能，可被观察

packages/core/types/wx/lib.wx.api.d.ts
=> fix(core-wx-types): 修复reportAnalytics和reportMonitor的参数顺序问题

packages/cli/core/compile.js, packages/cli/core/fileDep.js, packages/cli/core/plugins/parser/script.js, packages/compiler-babel/index.js, packages/compiler-babel/package-lock.json, packages/compiler-less/index.js
优化 watch 时的编译速度，当改变文件是 .less 时，只会编译引用了这个 less 文件的相关 wpy 文件。
=> refactor(cli): 优化 watch 时改变的是 .less 文件时的编译速度

packages/core/test/weapp/class/Dirty.js, packages/core/test/weapp/observer/observerPath.test.js, packages/core/weapp/class/Dirty.js, packages/core/weapp/observer/array.js, packages/core/weapp/observer/index.js, packages/core/weapp/observer/observerPath.js
=> refactor(core): 重构 observerPath 有关代码，减少遍历次数，优化 pathMap 结构

packages/cli/core/plugins/parser/config.js
如果是组件的话，resolvedUsingComponents 没有替换上。
=> fix(cli): fix resolve usingComponents in wepy or weapp component

packages/cli/test/core/hook.test.js
=> test(cli): update Hook unit test

packages/cli/core/parseOptions.js, packages/cli/test/core/parseOption.test.js
=> feat(cli): added watchOption

packages/cli/core/compile.js, packages/cli/core/plugins/compiler/before.js, packages/cli/core/plugins/parser/component.js, packages/cli/core/util/const.js
=> fix(cli): fixed weapp file watch

packages/cli/core/compile.js, packages/core/dist/wepy.js, packages/core/weapp/init/lifecycle.js
仅仅是个建议，可能我的方法不够好。
由于 `custom-tab-bar` 比较特殊，除它之外没有别的组件会出现这种情况，所以我用了这种方法。
* 根据 [官方文档](https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html) 配置 `app` 的 `config` 
*  `custom-tab-bar/index.wpy` (或其他自定义后缀) 会自动编译
还有一个不明的问题：每打开一个页面（任意页面、非tabBar页面）都会创建一个新的组件实例，不知这个问题可否忽略
issue #2377
=> feat: added custom-tab-bar support

packages/cli/core/plugins/parser/config.js
问题：全局引用组件时，如果没有页面引用该组件，则该组件不会被编译
问题已修复
=> fix(cli): fixed app usingComponents missing build

packages/cli/core/compile.js
=> fix(cli): fixed build components repeat

packages/core/dist/wepy.js, packages/core/weapp/class/Base.js
_event[event] => _events[event]
=> fix: 修复$off的bug

packages/cli/core/compile.js, packages/cli/package-lock.json, packages/cli/package.json
加入 watching 时的防抖动处理。如果开发者一次保存多个文件，则会 build 整个 app。
原来的行为是如果一次保存多个文件，只会 build 第一个文件。
=> feat(cli): debounce for watching

packages/cli/package-lock.json, packages/cli/package.json
=> fix(cli): fixed missing dependence

package-lock.json, packages/cli/core/plugins/template/directives/v-on.js, packages/cli/test/core/fixtures/template/assert/v-on.wxml, packages/cli/test/core/fixtures/template/assert/v-on/0-7.tap.js, packages/cli/test/core/fixtures/template/assert/v-on/0-8.tap.js, packages/cli/test/core/fixtures/template/original/v-on.html
修复 bug。
`@tap.capture` 应该为 `capture-bind:tap` 而不是 `capture-bindtap`。
`@tap.capture.stop` 应该为 `capture-catch:tap` 而不是 `capture-catchtap`。
=> fix(cli): fixed capture-bind:xxx and capture-catch:xxx

packages/cli/core/plugins/helper/sfcCustomBlock.js, packages/cli/test/core/plugins/helper/sfcCustomBlock.test.js
=> fix(cli): fixed sfcCustomBlock

packages/core/shared/env.js
fix(core): 小程序引入插件时，array 的变异方法失效
=> fix(core): 小程序引入插件时，array 的变异方法失效

packages/core/ant/init/lifecycle.js, packages/core/dist/wepy.ant.js
=> fix: 修正支付宝小程onload事件不能正确调用的问题

packages/core/shared/constants.js, packages/core/weapp/init/lifecycle.js
=> feat(core): component pageLifetimes support

packages/core/weapp/init/props.js
=> fix:  prop.type support array

lerna.json, package.json, packages/babel-plugin-import-regenerator/package-lock.json, packages/babel-plugin-import-regenerator/package.json, packages/cli/package-lock.json, packages/cli/package.json, packages/compiler-babel/package-lock.json, packages/compiler-babel/package.json, packages/compiler-less/package-lock.json, packages/compiler-less/package.json, packages/compiler-postcss/package-lock.json, packages/compiler-postcss/package.json, packages/compiler-sass/package-lock.json, packages/compiler-sass/package.json, packages/compiler-stylus/package-lock.json, packages/compiler-stylus/package.json, packages/compiler-typescript/package.json, packages/core/package-lock.json, packages/core/package.json, packages/core/weapp/init/props.js, packages/plugin-define/package.json, packages/plugin-eslint/package-lock.json, packages/plugin-eslint/package.json, packages/plugin-uglifyjs/package.json, packages/redux/package.json, packages/use-intercept/package.json, packages/use-promisify/package.json, packages/x/package-lock.json, packages/x/package.json
=> Added changelog support

packages/cli/core/plugins/parser/script.js, packages/cli/test/core/fixtures/template/assert/bindClass.wxml
=> test(fixtures): fixed template fixture

package-lock.json, packages/cli/core/compile.js
=> feat(cli): show warning while detect independent Subpackages

packages/core/shared/constants.js
=> feat(core): add weapp lifecycles.

LICENSE, packages/compiler-sass/README.md, packages/compiler-sass/index.js, packages/compiler-sass/package-lock.json, packages/compiler-sass/package.json, packages/compiler-sass/src/index.js, packages/compiler-sass/test/helpers/generate.js
将 @wepy/compiler-sass 中依赖项 node-sass 改为 sass
=> 将 @wepy/compiler-sass 中依赖项 node-sass 改为 sass

packages/core/weapp/init/props.js
=> fix(core): 修复了 type 必填的问题

package-lock.json, package.json, packages/use-intercept/index.js, packages/use-intercept/install.js, packages/use-intercept/test/index.test.js, scripts/config.js
=> fix(intercept):  fixed import path in dist

packages/core/test/weapp/util/debug.test.js, packages/core/test/weapp/util/error.test.js, packages/core/test/weapp/util/index.test.js, packages/core/test/weapp/util/model.test.js, packages/core/test/weapp/util/next-tick.test.js
Several test cases of util have been added
=> test(core): add test case of util

README.md, README_EN.md, packages/babel-plugin-import-regenerator/README.md, packages/babel-plugin-import-regenerator/README_EN.md, packages/compiler-postcss/README.md, packages/plugin-define/README.md, packages/plugin-define/README_EN.md, packages/redux/README.md, packages/redux/README_EN.md, packages/use-intercept/README.md, packages/use-intercept/README_EN.md, packages/use-promisify/README.md, packages/use-promisify/README_EN.md, packages/x/README.md, packages/x/README_EN.md
修改了readme中的问题：
代码缩进和标签问题
packages中compiler-postcss中readme的格式问题
=> 更正了readme中的小问题

packages/core/shared/constants.js
用生命周期的方式在 wepy/packages/core 中添加了onShareTimeline()
=> 添加onShareTimeline()

packages/router/README.md, packages/router/core/config.js, packages/router/core/createRouter.js, packages/router/core/guard/createComponentGuard.js, packages/router/core/guard/createRouterGuard.js, packages/router/core/guard/globalGuard.js, packages/router/core/guard/guardManager.js, packages/router/core/guard/index.js, packages/router/core/index.js, packages/router/core/routeManager.js, packages/router/core/routerApi.js, packages/router/core/utils/getRealPageInfo.js, packages/router/core/utils/queue.js, packages/router/core/utils/urlParse.js, packages/router/doc/config.md, packages/router/doc/guard.md, packages/router/doc/instance.md, packages/router/doc/router.md, packages/router/doc/usage.md, packages/router/index.js, packages/router/install.js, packages/router/package.json
=> feat(router): add routeManger

packages/wepy/src/base.js
wepy的1版本不支持自定义的朋友圈和自定义的收藏，但是有很多像我这样公司还用着wepy1的小程序，还没法迁移成新的。所以麻烦合并一下。
=> 支持小程序自定义分享朋友圈和自定义收藏

packages/cli/core/plugins/parser/config.js
支持使用useExtendedLib导入weui，使用方式
```
{
navigationBarTitleText: 'WePY 2.0 Feature Demo',
usingComponents: {
"mp-icon": "raw:weui-miniprogram/icon/icon",
"mp-cells": "raw:weui-miniprogram/cells/cells",
"mp-cell": "raw:weui-miniprogram/cell/cell",
"mp-slideview": "raw:weui-miniprogram/slideview/slideview",
"mp-dialog": "raw:weui-miniprogram/dialog/dialog",
"mp-msg": "raw:weui-miniprogram/msg/msg"
}
}
```
编译后的结果为
```
{
"navigationBarTitleText": "WePY 2.0 Feature Demo",
"component": true,
"usingComponents": {
"mp-icon": "weui-miniprogram/icon/icon",
"mp-cells": "weui-miniprogram/cells/cells",
"mp-cell": "weui-miniprogram/cell/cell",
"mp-slideview": "weui-miniprogram/slideview/slideview",
"mp-dialog": "weui-miniprogram/dialog/dialog",
"mp-msg": "weui-miniprogram/msg/msg"
}
}
```
fix #2680
=> 支持useExtendedLib导入weui

packages/cli/core/plugins/parser/script.js, packages/cli/core/plugins/scriptDepFix.js
=> 增加对 json 文件格式的支持。
