Tencent/wepy

- packages/wepy-cli/src/wepy.js
> fix `npm run build` error

- CHANGELOG.md
- packages/wepy-cli/src/util.js
- packages/wepy-cli/template/src/pages/index.wpy
这样用户在自定义事件的时候可以直接写 `@xxx` 而不必须加上 `.user` 标识 `@xxx.user` 。
为了以防小程序升级 新增事件不在白名单内，在 wepy 没升级的前提下，开发者可以手工在 `wepy.config.js` 中加入 `nativeEvents: ['newEventName']` 配置来解决不在白名单问题。
如果说自定义事件名是和原生事件冲突，例如 `change` 的话，用户依旧可以使用 1.4.8 版本方式 `@change.user` 来绑定自定义事件。
> 对于原生事件做白名单

- packages/wepy-cli/src/util.js
后来思考了下，如果加了 tag 白名单做法，貌似再加上事件白名单就有点多余了；
现在就直接简化为 原生 tag 绑定就是 bind(catch) ，自定义组件就是 v-on: 。
不知以 @Gcaufy  判断来看是否还需要事件白名单。o(╯□╰)o
> 去掉事件白名单，只保留 tag 白名单

- packages/wepy-plugin-replace/src/index.js
wepy-plugin-replace 的配置项可以是一个数组，这时候构造函数里面 this.setting 这个属性应该被设置成一个数组，而不是一个对象。
> 修复 wepy-plugin-replace 的配置项为一个数组的时候无效的问题

- README.md
高校内的二手书信息发布平台，这两天白名单内测中，正式开放还得等几天，源码稳定后会开源，到时候会附上链接
> 添加上线小程序“阅邻二手书”

- packages/wepy-cli/src/wepy.js
* Leave empty or `.` when using `new` command will use current directory automatically.
> New命令支持使用当前目录 & 修复package.json会被copy覆盖的问题

- packages/wepy-cli/src/compile-script.js
当找不到依赖的时候，抛出的错误信息增加依赖当前模块的模块地址。可以方便定位异常
> 增加找不到依赖的异常信息

- packages/wepy/src/component.js
兼容repeat的for里面的变量为null,或者undefined这种非array类型的情况。
> 兼容repeat的for里面的变量为null,或者undefined这种非array类型的情况。

- packages/wepy/src/component.js
- packages/wepy/test/fake/com_c.js
> data as function

- packages/wepy/src/app.js
- packages/wepy/test/app.js
- packages/wepy/test/wxfake.js
支持 `uploadTask` / `downloadTask`，可监听上传 / 下载进度变化事件，以及取消上传 / 下载任务。
使用方式
```
wepy.uploadFile({
url: 'https://example.weixin.qq.com/upload', //仅为示例，非真实的接口地址
filePath: 'tempFilePath',
name: 'file',
})
.progress(res => {
console.log('上传进度', res.progress)
console.log('已经上传的数据长度', res.totalBytesSent)
console.log('预期需要上传的数据总长度', res.totalBytesExpectedToSend)
})
.abort(() => {
// todo sth 处理中断任务
console.info('uploadFile abort custom')
})
.then((res) => {
// todo sth
});
```
```
const resp = await wepy.uploadFile({
url: 'https://example.weixin.qq.com/upload', //仅为示例，非真实的接口地址
filePath: 'tempFilePath',
name: 'file',
})
.progress(res => {
console.log('上传进度', res.progress)
console.log('已经上传的数据长度', res.totalBytesSent)
console.log('预期需要上传的数据总长度', res.totalBytesExpectedToSend)
})
.abort(() => {
// todo sth …
```
> 支持 uploadTask / downloadTask

- packages/wepy-cli/src/compile-template.js
用目前的代码会输出：
``` html
<image mode="aspectFit" src="{{../icons/icon_sound.png}}" />
``` 
会导致微信开发者工具文件编译错误
> 修改repeat中组件不能使用静态属性的bug

- packages/wepy-cli/templates/template/wepy.config.js
The aliasFields config in the template is removed in favor of the DEFAULT_ALIASFIELDS (`['wepy', 'weapp', 'browser']`).
This should resolve https://github.com/leancloud/javascript-sdk/pull/529
> remove the aliasFields config in the template

- docs/md/doc.md
修复了几处跟现有代码不一致的地方：
1. watcher不止可以监听数值属性
2. 如果没有用.sync，则父组件属性修改后，子组件中对应的props不会更新
3. 获取组件名称的属性是this.$name， 而不是this.name
4. 添加注释：用了自定义事件则events中对应的函数不再执行。
5. 添加注释：wepy中的mixin执行顺序跟Vue中相反。
> 修复了几处跟代码功能不一致的地方

- docs/md/doc.md
默认混合模式例子中 访问 this.bar 应该返回 TestMixin  中的 bar, 即"bar defined by testMix" ; 另外注释中的 "." 没有必要，容易误解
> 修正 例子中展示结果错误

- packages/wepy-ant/src/base.js
修复 wepy-ant 里事件处理函数获取dataset引起bug.
微信版本： 'wpy' + method.toLowerCase()
支付宝版本： 'wepyParams'
> bugfix:事件处理函数获取dataset. 由 'wepyParams' 变更为 'wpy' + method.toLowerCase()

- packages/wepy-cli/bin/wepy.js
- packages/wepy-cli/package-lock.json
- packages/wepy-cli/package.json
- packages/wepy-cli/src/bin/wepy-build.js
- packages/wepy-cli/src/bin/wepy-init.js
- packages/wepy-cli/src/bin/wepy-list.js
- packages/wepy-cli/src/bin/wepy-upgrade.js
- packages/wepy-cli/src/bin/wepy.js
- packages/wepy-cli/src/cli/ask.js
- packages/wepy-cli/src/cli/check-version.js
- packages/wepy-cli/src/cli/download.js
- packages/wepy-cli/src/cli/eval.js
- packages/wepy-cli/src/cli/filter.js
- packages/wepy-cli/src/cli/generate.js
- packages/wepy-cli/src/cli/git-user.js
- packages/wepy-cli/src/cli/local-path.js
- packages/wepy-cli/src/cli/logger.js
- packages/wepy-cli/src/cli/options.js
>  wepy-cli: added wepy init && wepy list commander

- docs/md/doc.md
- packages/wepy-cli/src/util.js
- packages/wepy-cli/test/util.js
#####
fix #542 
支持 `@tap.capture` 和 `@tap.capture.stop` 的语法
> 支持capture事件

- packages/wepy-cli/templates/empty/wepy.config.js
- packages/wepy-cli/templates/template/wepy.config.js
仅仅在wepy-cli的模板代码中添加一个less的配置strictMath，解决默认情况下less忽略calc中表达式的单位强制计算的问题。比如calc(100vh - 80px)会编译成calc(20vh)。这个问题已经有人提出[issue](https://github.com/Tencent/wepy/issues/340)了
该配置具体说明参考[这里](https://less.bootcss.com/usage/#less-options-cross-platform-options)
> 使用less的严格模式以避免对calc的错误计算

- packages/wepy-cli/templates/empty/.wepyignore
- packages/wepy-cli/templates/empty/gitignore
- packages/wepy-cli/templates/template/.wepyignore
- packages/wepy-cli/templates/template/gitignore
修复.gitignore和.wepyignore中的输入错误
.DB_store应该是.DS_Store
> fix typo, rename .DB_S(s)tore to .DS_Store

- docs/md/doc.md
interceptor  sample  add super(), Otherwise, it will prompt 'unknown: 'this' is not allowed before super()' error.
> interceptor  sample  add super().

- packages/wepy-cli/src/compile-script.js
When compiling typescript scripts, the compiler need to know the file name of the original one to generate the right sourcemap.
*You do not have any test for compile-script yet*
> Add fileName to typescript compiler config

- docs/data/cases.json
是一个适用于 羽毛球业余团体 组织团队日常活动的助手，辅助召集报名 报名后生成对阵表 计分 和排名等
> 增加 羽球自由对阵赛 项目

- packages/wepy-cli/src/compile-template.js
- packages/wepy/src/component.js
在循环组件中为了让子组件也能动态绑定，按照 @coolhwm 的建议 #1012 采用<repeat>循环数组的方式让子组件能动态绑定数据
但是有个问题，子组件中method方法无法工作，因为不能正确处理 <code>"[data]"</code> 这样的绑定
像下面这样，onTap将无法工作。因此对组件<code>$setIndex</code>做了些改进。
```xml
<repeat for="{{ [ data ] }}" item="data" index="i" key="i">
<child :data.sync="data"></child>
</repeat>
```
```xml
<template>
<view @tap="onTap({{data}}">点我</view>
</template>
```
> 修复repeat组件for="{{[var1,var2]}}"时的数据绑定问题，以及组件内capture事件问题修复

- packages/wepy-plugin-imagemin/package.json
- packages/wepy-plugin-imagemin/src/index.js
添加wepy-plugin-imagemin的svg支持，使bulid时可配置svg压缩
> 添加wepy-plugin-imagemin的svg支持

- README.md
- docs/md/api.md
- docs/md/doc.md
- package-lock.json
- packages/wepy-ant/src/app.js
- packages/wepy-cli/templates/template/src/pages/index-redux.wpy
- packages/wepy-cli/templates/template/src/pages/index.wpy
- packages/wepy/src/app.js
- packages/wepy/test/component.js
`new Date.getTime()` is significantly faster than `+new Date()`
and functionally equivalent
I'm sorry, my Chinese isn't very good, feel free to let me know if I am violating contribution guidelines.
Note that, as of when I forked this repo, `npm run test` had ~100 failures, so I did not fix those. 
Please see https://jsperf.com/new-date-timing for evidence that `+new Date()` is slow, and that `new Date.getTime()` is the fastest way to get a date number.
> Change all instances of +new Date() to new Date.getTime()

- packages/wepy-plugin-filemin/src/index.js
```
/mnt/hgfs/webprojects/guevara/node_modules/pretty-data/pretty-data.js:294
: text.replace(/\<![ \r\n\t]*(--([^\-]|[\r\n]|-[^\-])*--[ \r\n\t]*)\>/g,"");
```
解决打包异常
> fix: 解决由传入pretty-data的值为null时，引起的打包异常

- packages/wepy-cli/src/compile-script.js
添加eslint对扩展文件的支持，例如js/es/ts等
add eslintExt config
配置方式如下
```js
const config = {
wpyExt: '.wpy',
eslint: true,
eslintExt: '.js',
// eslintExt: ['.js', '.ts'],
}
```js
> 添加eslint对扩展文件的支持，例如js/es/ts等

- packages/wepy-web/src/base.js
toweb编译过程中，是先编译wpy，再编译vue组件，导致stylelist队列中vue组件中的style索引值相对wpy的靠后，最终导致的结果是：在runtime中，生成inject style的时候，wpy中的class样式会被vue组件中默认样式覆盖，具体重现见对应issue
解决方式：反转stylelist队列，使vue组件默认样式排在wpy之前
> fix(wepy-web): fix style inject sort (#1645)

- packages/cli/core/plugins/template/directives/v-on.js
当前事件名带有 ```-```横杠格式的命名方式时，编译结果如下：
``` 
handler: {'0': {index-emit: function proxyHandlerWithEvent ($event) {
var _vm=this;
return (function () {
_vm.counterEmit($event)
})();
}}}
```
经过 ``` JSON.stringify``` 处理后：
```
handler: {'0': {"index-emit": function proxyHandlerWithEvent ($event) {
var _vm=this;
return (function () {
_vm.counterEmit($event)
})();
}}}
```
> fix(cli): fixed proxyHandler key

- packages/core/dist/wepy.js
- packages/core/weapp/apis/index.js
- packages/core/weapp/apis/mixin.js
- packages/core/weapp/init/mixins.js
- packages/core/weapp/wepy.js
添加了全局 ```mixin```
e.g ：
``` javascript
wepy.mixin({
created () {
console.log('global mixin created')
}
})
```
> feat(core): added global mixin api

- packages/babel-plugin-import-regenerator/index.js
- packages/babel-plugin-import-regenerator/package.json
- packages/babel-plugin-import-regenerator/test/fixtures/normal/actual.js
- packages/babel-plugin-import-regenerator/test/fixtures/normal/expected.js
- packages/babel-plugin-import-regenerator/test/index.test.js
```bash
babel-plugin-import-regenerator
✓ should work with normal (944ms)
1 passing (950ms)
```
> test(babel-plugin-import-regenerator): added fixture tests

- docs/md/doc.md
修复 使用手册中的一处代码错误
`data-index={{index}}` 应改为 `data-index="{{index}}"`  需要加双引号
ps: 第一次向重要开源项目提pr，很激动嘻嘻
> fix: fix documents

- packages/cli/core/compile.js
- packages/cli/core/plugins/build/components.js
- packages/cli/core/plugins/scriptDepFix.js
修复在windows环境中usingComponents及require时的错误路径
- require
修复后
- usingComponents
修复后
> fix(cli): Fix the wrong path when usingComponents and require in windows environment

- packages/cli/core/compile.js
compatible subpackges or subPackges in app config
```app.wpy```
```vue
<config>
{
subPackages: [
{
root: ''",
name: "",
pages: []
}
]
}
</config>
```
or
```vue
<config>
{
subpackages: [
{
root: ''",
name: "",
pages: []
}
]
}
</config>
```
> feat(cli): support subpackages / subPackges

- packages/wepy-cli/src/compile-template.js
组件中使用wxs事件，会被当作组件变量编译成$parent$wxs这种形式，实际上这里不应该被处理
- 修复组件中使用wxs事件不生效的问题
Issue #2068
Close #2068
> fix: 修复组件中使用wxs事件

- packages/core/weapp/init/lifecycle.js
1. fix(core): 调用 app 生命周期传参错误
2. fix(core): 页面生命周期定义位置错误
使用 Component 构造器构造页面，页面的生命周期方法（即 on 开头的方法），应写在 methods 定义段中
> fix(core): patchAppLifecycle 和 patchLifecycle

- packages/core/weapp/native/app.js
1. 类的定义统一采用 es6 的写法
2. 注册 App 缺少 patchMixins
> refactor(core): WepyComponent 的 $nextTick 属性定义改为 es6 写法 和 fix(core): 注册 App 缺少 patchMixins

- packages/core/weapp/observer/array.js
- packages/core/weapp/observer/index.js
- packages/core/weapp/observer/observerPath.js
由于把 setData 的操作透明化了，所以在实际开发中就可能会出现复杂引用的情况。
比如：data 有两个属性 a 和 b。a 赋值给了对象 c，然后 b 也赋值给了对象 c。那么对 c 里某个属性做赋值操作，在放入 $dirty 时，实际应该是会有两组 path，'a.x' 和 'b.x'，而目前只会放入一组 'a.x'。这算比较简单的情况，更复杂可能出现很多这种嵌套的菱形关系。
#2256 是这个问题的一个数组情况特例，
> refactor(core): $dirty 的 path 考虑复杂相互引用的情况

- packages/core/weapp/init/lifecycle.js
- packages/core/weapp/init/props.js
- packages/core/weapp/init/render.js
1. fix(core): 修复 if (prop.default) 会发生隐身转换，导致部分默认值设置无效
2. fix(core): 修复 vm._init 为 false 时，setData 调用可能发生乱序的问题。因为下一个 setData 可能会比 nextTick setData 先执行
> fix(core): 不恰当的隐式转换和 setData 调用可能乱序

- packages/core/weapp/init/props.js
#2210 如此 issue 讨论的问题
不过还有两个问题没解决：
1. 当 changePaths 长度为 1 时，没法区分是组件内赋值还是父组件 WXML 数据绑定
2. 这是个 bug，跟本次 PR 无关。当有一个prop，父组件赋值为 a，然后组件赋值为 b，然后父组件再赋值为相同的 a，不会触发 setData，因为父组件内容没有变，set 里直接返回了，没有触发 notify。
解决方案：多写一次赋值，先赋值为其他值，再赋值回来（this.prop = x; this.prop = a）；或者修改 set 去掉 set 里的比较，后者得考虑会不会产生其他影响。
> refactor(core): 优化 observerFn 的实现

- packages/cli/core/compile.js
- packages/cli/core/plugins/parser/wxs.js
- packages/cli/package-lock.json
1. 原 wxs 解析的时候会有个问题是：如果 wxs 标签块是内联代码，解析后会导致 compiled 里面此 wpy 文件的 hash 会去掉，这样缓存就失效了。优化改为如果 wxs 是内联代码而整个文件的 hash 又没有变化时不去 compile；如果 wxs 是外部文件则保持原来的逻辑。
2. `applyCompiler()`  中原来直接更改了 involved[ctx.file] 的值。但如果是编译 wxs 外部文件的代码时， 此时 ctx.file 是外部文件的路径，也会被直接改掉。而 involved[ctx.file] 的值在这种情况下应该还是要记录对应 wpy 文件的路径，这样在 watch 中对应的代码才会执行，清除掉 wpy 文件的 hash。所以这里做了判断，如果 node 有 src，则不清除。
> refactor(core): 优化 wxs 解析逻辑 与 applyCompiler 中关于 involved 的修改逻辑

- .editorconfig
- packages/cli/core/compile.js
- packages/cli/core/tag.js
- packages/cli/test/core/tag.test.js
原来 watch 在重新编译时会每次都从入口开始，现在优化为如果更改的文件是 wpyExt 则只编译改变的文件。拿我们实际重构的项目测试速度提升明显，后面将继续优化其他类型的引用文件。
我们的项目就是 #2263 楼主提到的。
> refactor(cli): 优化 watch 时的编译效率和一些潜在问题

- packages/cli/core/compile.js
- packages/compiler-less/index.js
重构了 watch() 时的执行逻辑，利用 hook 分发给对应的 compiler 处理。
> refactor(cli): 优化 watch 时利用 hook 分发给对应的 compiler 处理

- packages/cli/core/fileDep.js
- packages/cli/core/plugins/parser/wpy.js
- packages/cli/test/core/fileDep.test.js
- packages/compiler-less/index.js
- packages/compiler-less/test/index.test.js
优化 FileDep，在 hash 改变时清除依赖，分发到 compile 或 parser 时收集依赖。
下一个 commit 会替换 `this.involved`。
> refactor(cli): 优化 FileDep 并加入单元测试

- packages/cli/bin/wepy-build.js
- packages/cli/core/compile.js
- packages/cli/core/parseOptions.js
- packages/cli/index.js
- packages/cli/package.json
nodejs api support
```javascript
const compiler = require('@wepy/cli')
const compilation = compiler({
entry: 'app',
watch: true,
// ... other options
})
compilation.run()
.catch(e => {
// error handler
})
```
> feat(cli): support nodejs api

- packages/cli/core/compile.js
- packages/cli/core/plugins/scriptInjection.js
解决在组件中插入重复的 template.parsed.rel 问题，在 watch 时也不会发生重复。
> fix(cli): fixed import duplicated template.parsed.rel

- packages/cli/core/plugins/template/parse.js
- packages/cli/test/core/fixtures/template/assert/attrWithoutValue.wxml
- packages/cli/test/core/fixtures/template/original/attrWithoutValue.html
- packages/cli/test/core/plugins/template/parse.test.js
修复一个 bug，当 attr 没有值时，比如：
```html
<view hidden></view>
```
代码会被解析为：
```html
<view hidden=""></view>
```
当使用 `<scroll-view>` 这种组件时会比较多的使用到这种属性声明方式。
> fix(cli): fixed attr without value

- packages/cli/core/plugins/template/attrs/bindStyle.js
- packages/cli/test/core/fixtures/template/assert/bindStyle.wxml
- packages/cli/test/core/fixtures/template/original/bindStyle.html
- packages/cli/test/core/plugins/template/parse.test.js
修正一个 bug，比如 :style 时用了三元表达式：
```html
<view :style="{ 'background': current === idx ? dotActiveColor : dotColor }"></view>
```
代码会被解析为：
```html
<view style=" {{ 'background:' + current === idx ? dotActiveColor : dotColor + ';' }}"></view>
```
解决方案是用括号恢复优先级。
> fix(cli): fixed priority of "+" operator for bindStyle

- packages/cli/core/plugins/template/parse.js
- packages/cli/test/core/fixtures/template/assert/joinStyle.wxml
- packages/cli/test/core/fixtures/template/original/joinStyle.html
- packages/cli/test/core/plugins/template/parse.test.js
修正拼接 `style` 与 `:style` 时中间缺少分号的问题。
> fix(cli): fixed join staticStyle and bindStyle

- packages/cli/core/compile.js
`Parser`类组件通过`hookUnique`调用时只会执行最后一次注册的方法，所以自定义插件要想覆盖注入，必须在 `initParser()`之后进行注入
> 调整自定义组件注册与Parser组件注册顺序

- packages/cli/core/plugins/scriptInjection.js
- packages/cli/core/plugins/template/attrs/ref.js
- packages/cli/core/plugins/template/parse.js
- packages/cli/test/core/fixtures/template/assert/ref.wxml
- packages/cli/test/core/fixtures/template/original/ref.html
- packages/cli/test/core/plugins/template/parse.test.js
- packages/core/dist/wepy.js
- packages/core/weapp/init/lifecycle.js
#1789 
ref 被用来给元素或子组件注册引用信息。引用信息将会注册在父组件的 $refs 对象上。如果在普通的小程序元素上使用，引用指向的就是小程序元素 SelectorQuery 对象实例；如果用在子组件上，引用就指向组件实例：
```vue
<template>
<view ref="view">hello</view>
<view :ref="viewRefValue">hello</view>
<child-component ref="child"></child-component>
<child-component :ref="childRefValue"></child-component>
</template>
<script>
// ...
data: {
viewRefValue: 'view2',
childRefValue: 'child2'
}
</script>
```
暂不支持在 `v-for` 中使用 `ref` 特性
> test(cli): support bind ref 

- packages/cli/core/plugins/template/attrs/ref.js
- packages/cli/test/core/fixtures/template/assert/ref.wxml
- packages/cli/test/core/fixtures/template/original/ref.html
- packages/core/dist/wepy.js
- packages/core/weapp/init/lifecycle.js
ref 被用来给元素或子组件注册引用信息。引用信息将会注册在父组件的 $refs 对象上。如果在普通的小程序元素上使用，引用指向的就是小程序元素 SelectorQuery 对象实例；如果用在子组件上，引用就指向组件实例：
```vue
<template>
<view ref="view">hello</view>
<view :ref="viewRefValue">hello</view>
<child-component ref="child"></child-component>
<child-component :ref="childRefValue"></child-component>
</template>
<script>
// ...
data: {
viewRefValue: 'view2',
childRefValue: 'child2'
}
</script>
```
暂不支持在 `v-for` 中使用 `ref` 特性
ref 被用来给普通小程序元素注册引用信息
编译期检测到元素有使用 ref 属性时，会动态给元素创建一个唯一 id，通过代码注入的方式传入运行时的 `page` 构造器。
运行时中，通过获取构造器中的 `id` 和 `ref` 信息，页面会在  `attach` 生命周期中创建元素的节点 SelectorQuery 对象并初始化页面实例的 `$refs` 属性
当某个小程序元素 id 与 ref 属性同时存在时，如：
- 编译前
```vue
<view id="myId" ref="myRef"></view>
//...
{
myLogic () {
const query = SelectorQuery.select('#myId')
// ...
}
}
```
由于之前没有对这种情况进行兼容，编译后会导致初始的 id …
> fix: fixed ref not work when id and ref attr exist at the same time

- packages/core/ant/native/app.js
- packages/core/ant/native/index.js
- packages/core/dist/wepy.ant.js
引用weapp下的app.js时，会导致wepy.ant.js输出多余的 `callUserMethod$1` 等方法，通过对比wepy.js和wepy.ant.js难以排查问题
> fix: 更改引用app.js, 导致wepy.ant.js生成多余的方法

- packages/core/weapp/observer/scheduler.js
fix(core): #2448
原因是 flushSchedulerQueue  里，递归调用时，index 每次都从 0 开始。并且每次调用后 pendingQueue 都不为空， 因此递归无法终止
> fix(core): #2448

- packages/cli/core/plugins/parser/config.js
- packages/cli/core/plugins/scriptDepFix.js
- packages/cli/core/plugins/template/attrs/src.js
在 app.wpy 中的 config 里写的 `usingComponent` 路径，会被合并到每一个组件中。
使用 `path` 包中的 API，会根据操作系统的不同选择对应的路径分隔符（Windows 使用 `\`，在 JSON 中会被转义成 `\\`，在 *nix 中使用 `/`）。但微信小程序只能识别 `/`，故而找不到组件路径。
因此在 Windows 系统中使用时，遇到了问题。
可以增加一个字符串替换，将 `\` 变为 `/`，此时 Windows 路径会正确处理，*nix 不受影响。
> 修正从 app.wpy 复制 usingComponents 属性至组件的路径 bug（Windows 系统）

- packages/cli/core/plugins/template/directives/condition.js
- packages/core/types/options.d.ts
- packages/core/types/wepy.d.ts
在使用 TypeScript 时发现问题，观察到该文件（`options.d.ts`）第 24 行：
```typescript
ComponentOptions<V, DataDef<Data, Record<PropNames, any>, V>, Methods, Computed, PropNames[], Record<PropNames, any>>
```
以及第 32 行：
```typescript
ComponentOptions<V, DataDef<Data, Props, V>, Methods, Computed, RecordPropsDefinition<Props>, Props>
```
调用 `ComponentOptions` 时传递了六个参数，而该类型的定义为（第 49 行至第 77 行，截取参数部分）：
```typescript
export interface ComponentOptions<
V extends WepyInstace,
Data=DefaultData<V>,
Methods=DefaultMethods<V>,
Hooks=DefaultHooks<V>,
Computed=DefaultComputed,
PropsDef=PropsDefinition<DefaultProps>,
Props=DefaultProps> extends wepy.Page.PageInstance {
```
传入了 7 个参数。
经比对，发现第四个参数 `Hooks` 没有被使用，因此调用时的 `Computed` 被错误地传入了 `Hooks` 里，后面的以此类推，第七个参数被迫使用默认值。
翻阅文档，未发现有 Hooks 的任何记载（可能我看得不仔细），因此先注释掉（以及返回类型里用到 `Hooks` 的 …
> Fix TypeScript type definition bug

- .eslintrc
- packages/cli/core/plugins/parser/config.js
- packages/use-intercept/package.json
1. add useComponents in app.json
2. remove global components from page's json file
3. compile component file in app.json
#2559 
在windows系统中使用全局组件的时候发现一个问题。
重现过程如下
1. 在src/components/ 中创建组件a.wpy
2. 在app.wpy的config 中useComponents引用a.wpy，
```
useComponents:{
a: "component/a"
}
```
3. 在编译的weapp/app.json中并没有useComponents属性。在weapp/components文件夹中也无对应组件的编译文件。
4. 在每个页面及组件的 json文件中的 useComponents 都能发现一个配置项
```
a:"..\\components\\a"
```
- 初步判断原因应该是全局组件解析path时文件路径都为 '..\\..\\'形式，JS无法解析导致页面打包时找不到对应的文件，因此打包被跳过
- 由于该a组件的编译文件并没有被打包到 weapp/components 文件夹中，且该应用方式不能被JS解析，导致页面中引用组件报错，不能正常使用a组件。
- 同时a组件会在所有页面及组件进行引用，无形中会细微的增加一点打包体积。
因此原来的全局组件打包方式亟需需要优化
研究@wepy/cli/core发现在代码中找到现在实现全局组件的方式
1. 在解析config 时，app.json中的useComponents 被删掉，然后添加进每个页面及组件内
```
126     if (ctx.type === 'app') {
127 …
```
> Global components

- packages/wepy-compiler-sass/src/index.js
解决 无法添加全局 scss 的问题
使用示例:
```
sass: {
data: '$color: lightblue;'
}
```
但无法直接使用以下方式引入scss文件（可能是不支持对路径的解析导致）
```
sass: {
data: '@import "@/static/css/_var.scss";'
}
```
当需要引入scss文件时，可使用如下方式：
```
const fs = require('fs')
const commonScss = fs.readFileSync('./src/static/css/_var.scss')
sass: {
data: commonScss
}
```
> feat(wepy-compiler-sass): 添加对 node-sass data 字段配置的支持

- packages/core/dist/wepy.js
- packages/core/test/weapp/init/lifecycle.test.js
- packages/core/weapp/init/lifecycle.js
按照文档修正了”生命周期函数补充与修改“的行为，已加入单元测试；并将 `getLifecycycle` 重命名为 `getLifeCycle`。
> fix(core): correct getLifeCycle and add tests.

- packages/core/test/mock/api/createSelectorQuery.js
- packages/core/test/mock/wxapi.js
- packages/core/test/weapp/init/lifecycle.test.js
- packages/core/test/weapp/observer/observerPath.test.js
- packages/core/weapp/init/lifecycle.js
Used to handle page route events.
navigate or navigateBack will both trigger this event.
```
wepy.page({
// If it's the first time to enter a page, then previous route is null
routed(previousRoute, currentRoute) {
console.log(`Routed event triggerd: ${previousRoute === null ? 'Started' : previousRoute.path} -> ${currentRoute.path}`);
}
})
```
PS: test cases included.
> feat: added routed lifecycle

- test/unit.js
在 windows 下 npm 的执行名不同。
这里判断了一下平台。
> 支持 windows 下的 npm run test:cov 命令

- packages/cli/core/tag.js
live-player & live-pusher 是双标签不是单标签
单标签无法包裹cover-view 有场景需要在组件内添加内容
> 【hotfix】live-player & live-pusher 是双标签不是单标签

- packages/wepy-cli/src/compile-script.js
- packages/wepy-cli/src/web/compile-script.js
- packages/wepy-compiler-typescript/package.json
目录结构如下：
```
.
├── other.ts
├── test
│   └── index.ts
```
other.ts代码如下：
```typescript
import { test } from './test';  // 报错
import { test } from './test/index';  // ok
```
在ts里，import 简写为目录名'./test'时报错`[Error] Missing files: ./test in /xxxxxxx/other.ts`
> 修复ts import不能简写为目录名的问题

- packages/cli/core/compile.js
这里拼接的时候应该用 options.output 而不是 options.target
@Gcaufy
> fix(output-static): dest 路径拼接的错误
